apiVersion: kapy.sh/v1
kind: ControlPlane
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: controlplane-sample
spec:
  # TODO(user): Add fields here
