apiVersion: kapy.sh/v1
kind: ControlPlane
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: controlplane-sample
spec:
  server:
    image: ghcr.io/kapycluster/kapyserver:master
    persistence: sqlite
    token: dummy
  network:
    loadBalancerAddress: 100.99.148.52
