apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel
  template:
    metadata:
      labels:
        app: panel
    spec:
      containers:
        - name: panel
          image: ghcr.io/kapycluster/panel:master@sha256:9746a02765b9e5dbdf8f94a461b943a029423838b95d32b44d92f6f014753419
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - "-c"
            - "/root/panel"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: panel-env
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: panel
spec:
  selector:
    app: panel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: panel
  annotations:
    ingress.class: "haproxy"
spec:
  rules:
    - host: panel.kapycluster.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: panel
                port:
                  number: 80
