# permissions for end users to edit
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: cluster-editor-role
rules:
- apiGroups:
  - kapy.sh
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapy.sh
  resources:
  - controlplanes/status
  verbs:
  - get
