---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kapy.sh
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapy.sh
  resources:
  - controlplanes/finalizers
  verbs:
  - update
- apiGroups:
  - kapy.sh
  resources:
  - controlplanes/status
  verbs:
  - get
  - patch
  - update
