[build]
pre_cmd = [
    "cd views && npx tailwindcss -i ./input.css -o ./static/style.css",
    "templ generate",
]
cmd = "go build -o panel ../cmd/panel/main.go"
bin = "panel"
root = "."

exclude_regex = [".*_templ.go"]
include_ext = ["go", "templ"]
