name: build and push (panel)

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
    paths:
      - "panel/**"
      - "docker/panel.dockerfile"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kapycluster/panel
  DOCKERFILE: docker/panel.dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build container and push to registry
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ env.DOCKERFILE }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
